language: node_js
dist: trusty
sudo: required
node_js:
- '8'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - release-0.5.0
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
addons:
  chrome: stable
deploy:
  provider: heroku
  api_key:
    secure: 8d1dd2e7-e9a5-47da-ae76-f427b9c70f4c
  app: ngx-text-diff
  on:
    repo: ABenassi87/ngx-text-diff
    branch: release-0.5.0
